[
  {
    "source": "https://github.com/nodejs/node/pull/21227/",
    "upstream": "https://ci.nodejs.org/job/node-test-commit/19123/",
    "type": "JS_TEST_FAILURE",
    "url": "https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian9-64/19446/console",
    "reason": "not ok 2178 sequential/test-inspector-port-zero-cluster\n  ---\n  duration_ms: 0.272\n  severity: fail\n  exitcode: 1\n  stack: |-\n    Debugger listening on ws://127.0.0.1:45799/0523bc03-e8b2-43fc-aafa-d246cee6800c\n    For help, see: https://nodejs.org/en/docs/inspector\n    Debugger listening on ws://127.0.0.1:45800/544f1c62-d55e-4ea7-85bc-d73edb36ea88\n    For help, see: https://nodejs.org/en/docs/inspector\n    Debugger listening on ws://127.0.0.1:45801/02db6a20-090d-43f0-8be4-9dff885ffd6f\n    For help, see: https://nodejs.org/en/docs/inspector\n    Starting inspector on 127.0.0.1:45802 failed: address already in use\n    node: ../deps/uv/src/unix/core.c:117: uv_close: Assertion `!uv__is_closing(handle)' failed.\n    assert.js:80\n      throw new AssertionError(obj);\n      ^\n    \n    AssertionError [ERR_ASSERTION]: code: null, signal: SIGABRT\n        at Worker.worker.on.common.mustCall (/home/iojs/build/workspace/node-test-commit-linux/nodes/debian9-64/test/sequential/test-inspector-port-zero-cluster.js:20:16)\n        at Worker.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux/nodes/debian9-64/test/common/index.js:451:15)\n        at Worker.emit (events.js:182:13)\n        at ChildProcess.worker.process.once (internal/cluster/master.js:193:12)\n        at Object.onceWrapper (events.js:273:13)\n        at ChildProcess.emit (events.js:182:13)\n        at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)\n  ...\n",
    "highlight": 0,
    "file": "sequential/test-inspector-port-zero-cluster",
    "severity": "fail"
  }
]